version: '3'
services:
  app:
    build: app
    ports:
      - "8080:80"
    environment: 
      - PRODUCTS_URL=http://products:8080
      - DEBUG=true
  products:
    image: "gcr.io/cloud-run-book/product"
    environment:
      - PORT=8080